server:
  port: 9001
spring:
  application:
    name: onesquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.207.111:3306/tensquare_base?useUnicode=true&characterEncoding=UTF-8
    username: root
    data-password: itcast
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
